# Site settings
remote_theme: raviriley/agency-jekyll-theme

url    : "https://globalcyberdefenseunit.github.io"   # o seu domínio real
baseurl: "/GCDU"                                      # o nome do repositório

title       : Global Cyber Defense Unit
email       : GCDU@protonmail.com
description : "Independent cyber defense unit protecting people and privacy since 2015."
author      : GCDU

locale: "en-US"

analytics:
  google:

collections:
  portfolio:

markdown: kramdown

# formspree_form_path: "f/o_seu_id_aqui"   # descomente depois de criar conta no Formspree

plugins:
  - jekyll-remote-theme
